variables:
  IMAGE_NAME: $CI_BUILD_RG/orvice/${CI_PROJECT_NAME}
  BIN_OUTPUT: bin/monitor-client
  DEB_OUTPUT: bin/monitor-client.deb

image: docker:latest
services:
  - docker:dind
stages:
  - test
  - build
  - build-debian
  - deploy

include:
  - project: 'ops-public/ci-templates'
    file: 'build/go-docker.yml'

build-bin:
  image:
    name: golang:1.16
  stage: build
  tags:
    - docker
  artifacts:
    paths:
      - $BIN_OUTPUT
  script:
    - go mod download
    - make build

build-deb:
  image:
    name: debian
  stage: build-debian
  tags:
    - docker
  artifacts:
    paths:
      - $DEB_OUTPUT
  script:
    - ./build/build_deb.sh
    - ls