variables:
  APP_NAME: monitor-client
  IMAGE_NAME: $CI_BUILD_RG/orvice/${CI_PROJECT_NAME}
  BIN_OUTPUT: bin/monitor-client
  DEB_PKG: monitor-client_${CI_COMMIT_REF_NAME}-1_amd64

image: docker:latest
services:
  - docker:dind
stages:
  - test
  - build
  - build-debian
  - deploy

include:
  - project: 'ops-public/ci-templates'
    file: 'build/go-docker.yml'

build-bin:
  image:
    name: golang:1.16
  stage: build
  tags:
    - docker
  artifacts:
    paths:
      - $BIN_OUTPUT
  script:
    - go mod download
    - make build

build-deb:
  image:
    name: debian
  stage: build-debian
  tags:
    - docker
  artifacts:
    paths:
      - ${DEB_PKG}.deb
  script:
    - ./build/build_deb.sh

deploy:
  stage: deploy
  image: quay.io/orvice/ubuntu-full
  tags:
    - docker
  environment:
    name: production
  script:
    - rclone config file
    - echo "${RCLONE_CONF}" >> /root/.config/rclone/rclone.conf
    - rclone copy ${DEB_PKG}.deb  ${RCLONE_DST}/deb/${DEB_PKG}.deb
  only:
   - master
   - tags
