version: "2"

services:
  ss:
    image: orvice/monitor-client
    restart: always
    volumes:
      - ./log:/var/log
    environment:
      - NET_INTERFACE=eth0
      - WEB_ADDR=:8080
      - GRPC_ADDR=:8090
    container_name: monitor-client
    network_mode: host
 
