version: "2"

services:
  monitor-client:
    image: quay.io/orvice/monitor-client:latest
    restart: always
    volumes:
      - ./log:/app/log
    environment:
      - NET_INTERFACE=eth0
      - WEB_ADDR=:8080
      - GRPC_ADDR=:8090
      - POST_URL=https://demo.pokemon.men/nodes/1
      - POST_KEY=key
    container_name: monitor-client
    network_mode: host
 
